### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nasa/jeod#3]
I would like to point out that identifiers like “[`_DEG2RAD`](https://github.com/nasa/jeod/blob/464b37b830e04b1e12486947a5db67bd61723394/models/environment/spice/verif/compare/include/io_utils.hh#L40 "Update candidate")” and “[`_ORB_ELEM_MULTI_VER_H_`](https://github.com/nasa/jeod/blob/464b37b830e04b1e12486947a5db67bd61723394/models/utils/orbital_elements/verif/SIM_orb_elem/models/orb_elem_ver/include/orb_elem_multi_ver.hh#L62 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by DavidHammen** [comment]
I rejoined GitHub just to comment on this. All identifiers that start with a double underscore are strictly reserved for use by the implementation (the compiler, the linker, etc.), as are all identifiers starting with a single underscore and immediately followed by an uppercase letter. In some places identifiers starting with a single underscore are strictly reserved as well. Violating this invokes undefined behavior, which means no diagnostic is required.

The easy solution to this is to never use any identifier that starts with a leading underscore. IIRC, that easy solution used to be in the JEOD coding standards.

Equally alarming is the `using namespace std` in jeod/models/environment/spice/verif/compare/include/io_utils.hh. While I understand that this is just verif code, but `using namespace std` does not belong in any header file.

**Comment by excaliburtb** [comment]
thank you for the comments. this was legacy code from 2017 introduced by another team and hasn't been touched since then. As you said, it is for verification purposes, so it hasn't been audited or anything in a while. We created an issue to take care of it.

**Comment by elfring** [comment]
>We created an issue to take care of it.

To which issue tracker do you refer here?

**Comment by excaliburtb** [comment]
We have an internal issue system that encompasses both the open-source and JSC internal content

**Comment by zli0** [comment]
issue addressed in [JEOD v5.1](https://github.com/nasa/jeod/releases/tag/jeod_v5.1)

**Comment by DavidHammen** [comment]
@elfring All of JEOD used to restricted per the International Traffic in Arms Regulations (ITAR). The vast majority of JEOD has since had those ITAR restrictions removed, thereby enabling those unrestricted portions of JEOD to be released as NASA open source. Because a small portion of JEOD remains ITAR-restricted, JEOD is not maintained on GitHub (GitHub is not ITAR compliant). Instead, JEOD is maintained internally using ITAR-compliant (and also CMMI level 3 compliant) processes and tools. Upon making an internal JEOD release, a clone of the internal JEOD repo is made, but with the ITAR-restricted portions stripped out. This unrestricted clone then pushed to the open source version of JEOD as a single GitHub commit, which is why you see the rather useless commit message.
